apiVersion: v1
kind: Service
metadata:
  name: producer-service
spec:
  selector:
    app: producer-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer-deployment
  labels:
    app: producer-deployment
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: producer-deployment
  template:
    metadata:
      labels:
        app: producer-deployment
    spec:
      containers:
      - name: app
        image:  ko://knative.dev/async-component/cmd/async/producer
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "my-cluster-kafka-bootstrap.kafka:9092"
        - name: KAFKA_TOPIC
          value: "knative-demo-topic"
        - name: KAFKA_KEY
          value: "0"
        - name: KAFKA_HEADERS
          value: "content-type:application/json"
        ports:
        - containerPort: 80




        