# Note: this requires the redis operator from
# https://raw.githubusercontent.com/spotahome/redis-operator/master/example/operator/all-redis-operator-resources.yaml
# to be installed
apiVersion: databases.spotahome.com/v1
kind: RedisFailover
metadata:
  name: queue-store
spec:
  sentinel:
    replicas: 1
    resources:
      requests:
        cpu: 100m
      limits:
        memory: 100Mi
  redis:
    replicas: 1
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        cpu: 400m
        memory: 500Mi